.statistics.wavelet:
  PhaseSlopeIndex:
    configs:
    - fmax: 0.5
      fmin: 0
      statistic: max
    dependencies:
    labels:
    - undirected
    - unsigned
    - time/frequency dependent
    - bivariate
