services:
  metrics:
    build:
      context: .
      platforms:
        - "linux/amd64"
      dockerfile: Dockerfile_Metrics
    volumes:
      - ./:/app
  notebook:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/app