.statistics.spectral:
  CoherencePhase:
    configs:
    - fmax: 0.25
      fmin: 0
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
