.statistics.distance:
  HilbertSchmidtIndependenceCriterion:
    configs:
    - biased: false
    dependencies:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
