.statistics.basic:
  Covariance:
    configs:
    - estimator: EmpiricalCovariance
      squared: true
    dependencies:
    labels:
    - undirected
    - linear
    - signed
    - multivariate
    - contemporaneous
