.statistics.misc:
  PowerEnvelopeCorrelation:
    configs:
    - absolute: false
      log: true
      orth: false
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - time-dependent
