.statistics.infotheory:
  ConditionalEntropy:
    configs:
    - estimator: kernel
    dependencies:
    - java
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
