.statistics.infotheory:
  JointEntropy:
    configs:
    - estimator: kozachenko
    dependencies:
    - java
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
