.statistics.misc:
  PowerEnvelopeCorrelation:
    configs:
    - absolute: true
      log: false
      orth: true
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - time-dependent
