.statistics.basic:
  Precision:
    configs:
    - estimator: LedoitWolf
      squared: true
    dependencies:
    labels:
    - undirected
    - linear
    - signed
    - multivariate
    - contemporaneous
