.statistics.spectral:
  DirectDirectedTransferFunction:
    configs:
    - fs: 1
      statistic: max
    dependencies:
    labels:
    - directed
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
