.statistics.spectral:
  WeightedPhaseLagIndex:
    configs:
    - fmax: 0.25
      fmin: 0
      statistic: max
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
