.statistics.spectral:
  PhaseLagIndex:
    configs:
    - fs: 1
      statistic: max
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
