.statistics.spectral:
  PartialDirectedCoherence:
    configs:
    - fmax: 0.5
      fmin: 0.25
    dependencies:
    labels:
    - directed
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
