.statistics.infotheory:
  CrossmapEntropy:
    configs:
    - estimator: gaussian
      history_length: 1
    dependencies:
    - java
    labels:
    - unsigned
    - directed
    - time-dependent
    - bivariate
