.statistics.infotheory:
  TimeLaggedMutualInfo:
    configs:
    - estimator: gaussian
    dependencies:
    - java
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
