.statistics.misc:
  Cointegration:
    configs:
    - det_order: 1
      k_ar_diff: 1
      method: johansen
      statistic: trace_stat
    dependencies:
    labels:
    - undirected
    - linear
    - unsigned
    - bivariate
    - time-dependent
