.statistics.infotheory:
  StochasticInteraction:
    configs:
    - estimator: kernel
    dependencies:
    - java
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
