.statistics.spectral:
  PhaseSlopeIndex:
    configs:
    - fmax: 0.5
      fmin: 0.25
    dependencies:
    labels:
    - directed
    - linear/nonlinear
    - unsigned
    - bivariate
    - frequency-dependent
