.statistics.distance:
  Barycenter:
    configs:
    - mode: euclidean
      squared: true
      statistic: max
    dependencies:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
