.statistics.spectral:
  SpectralGrangerCausality:
    configs:
    - fmax: 0.5
      fmin: 0.25
      method: parametric
      statistic: max
    dependencies:
    labels:
    - directed
    - linear
    - unsigned
    - bivariate
    - frequency-dependent
