.statistics.basic:
  CrossCorrelation:
    configs:
    - squared: true
      statistic: max
    dependencies:
    labels:
    - undirected
    - linear
    - signed/unsigned
    - bivariate
    - time-dependent
